- platform: template
  covers:
    garage_door:
      device_class: garage
      friendly_name: "Garage Door"
      value_template: >-
        {% if is_state('binary_sensor.garage_door_tilt_sensor_window_door_is_open','on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      open_cover:
        service: switch.turn_on
        data:
          entity_id: switch.zooz_relay_2
      close_cover:
        service: switch.turn_on
        data:
          entity_id: switch.zooz_relay_2
      stop_cover:
        service: switch.turn_on
        data:
          entity_id: switch.zooz_relay_2
      icon_template: >-
        {% if is_state('binary_sensor.garage_door_tilt_sensor_window_door_is_open','on') %}
          mdi:garage-open-variant
        {% else %}
          mdi:garage-variant
        {% endif %}

